update verdaccio-pro

diff --git a/.github/workflows/apm.yml b/.github/workflows/apm.yml
--- a/.github/workflows/apm.yml
+++ b/.github/workflows/apm.yml
@@ -28,18 +28,24 @@ jobs:
     runs-on: ubuntu-latest
     if: github.repository == 'mbtools/verdaccio'
     steps:
-      - name: Check Verdaccio Pro Registry
-        run: |
-          set -e
-          if curl -sfL --max-time 10 https://registry.verdaccio.pro/ > /dev/null; then
-            echo "Verdaccio Pro Registry is reachable."
-          else
-            echo "ERROR: Verdaccio Pro Registry at https://registry.verdaccio.pro is NOT reachable." >&2
-            exit 1
-          fi
+#      - name: Check Verdaccio Pro Registry
+#        run: |
+#          set -e
+#          if curl -sfL --max-time 10 https://registry.verdaccio.pro/ > /dev/null; then
+#            echo "Verdaccio Pro Registry is reachable."
+#          else
+#            echo "ERROR: Verdaccio Pro Registry at https://registry.verdaccio.pro is NOT reachable." >&2
+#            exit 1
+#          fi
 
       - name: Checkout Repository
         uses: actions/checkout@v6
+
+      - name: Package Verdaccio Pro Plugins
+        run: |
+          cd abappm/plugins/@verdaccio-pro/database
+          pnpm pack
+          cd /
 
       - name: Copy Dockerfile for Root Build Context
         run: |
